"use client";

import { Component, useCallback, useEffect, useMemo, useState, type ErrorInfo, type ReactNode } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, Download, Heart, Search, Settings2, Sparkles, Trash2, X } from "lucide-react";
import { authFetch } from "@/lib/client-auth";
import { moduleCatalog, type ModuleManifest, type ModulePermission } from "@/lib/modules/catalog";
import { createHostSDK, type HostSDK, type HostTask } from "@/lib/modules/host-sdk";
import { ModuleSlotRegistry } from "@/lib/modules/registry";
import "@/app/apps.css";

type Installed = { moduleId: string; version: string; permissions: ModulePermission[]; enabled: boolean };
type Props = { moduleId?: string; userName: string; onOpenModule: (id: string) => void; onOpenStore: () => void; onInstalledChange?: (items: Installed[]) => void };
type SavedRow = { id: string; [key: string]: unknown };
const categories = ["Daily Life", "Tasks", "Health", "Money", "Writing", "Research", "Learning", "Utilities"];
const api = async <T,>(url: string, init?: RequestInit): Promise<T> => {
  const response = await authFetch(url, { ...init, cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || `Daywell Apps returned ${response.status}.`);
  return body as T;
};

class ModuleErrorBoundary extends Component<{ children: ReactNode; resetKey: string }, { error: Error | null }> {
  state = { error: null as Error | null };
  static getDerivedStateFromError(error: Error) { return { error }; }
  componentDidCatch(error: Error, info: ErrorInfo) { console.error("Daywell module failed", { error: error.message, componentStack: info.componentStack }); }
  componentDidUpdate(previous: Readonly<{ resetKey: string }>) { if (previous.resetKey !== this.props.resetKey && this.state.error) this.setState({ error: null }); }
  render() { return this.state.error ? <div className="module-error" role="alert"><AlertTriangle size={20}/><b>This app hit a problem</b><p>Your Daywell workspace is safe. Reopen the app or return to the store.</p><button className="apps-button" onClick={() => this.setState({ error: null })}>Try again</button></div> : this.props.children; }
}

function ModulePanel({ manifest, permissions, userName }: { manifest: ModuleManifest; permissions: ModulePermission[]; userName: string }) {
  const host = useMemo(() => createHostSDK(manifest, permissions), [manifest, permissions]);
  return <ModuleErrorBoundary resetKey={manifest.id}><div className="module-runner"><div className="module-runner-head"><div className="module-icon">{manifest.icon}</div><div><span>{manifest.category} · v{manifest.version}</span><h2>{manifest.name}</h2></div><span className="module-live"><i/> Installed</span></div><ModuleBody manifest={manifest} host={host} userName={userName}/></div></ModuleErrorBoundary>;
}

function ModuleBody({ manifest, host, userName }: { manifest: ModuleManifest; host: HostSDK; userName: string }) {
  if (manifest.id === "tasks") return <TasksModule host={host}/>;
  if (manifest.id === "habits") return <HabitsModule host={host}/>;
  if (manifest.id === "journal") return <JournalModule host={host} userName={userName}/>;
  if (manifest.id === "notes") return <NotesModule host={host}/>;
  if (manifest.id === "money") return <MoneyModule host={host}/>;
  return <p>This bundled app is not available in this version of Daywell.</p>;
}

function useCollection<T extends SavedRow>(host: HostSDK, key: string) {
  const [rows, setRows] = useState<T[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const reload = useCallback(async () => { setLoading(true); try { setRows((await host.storage.get<T[]>(key)) || []); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load saved data."); } finally { setLoading(false); } }, [host, key]);
  useEffect(() => { void reload(); }, [reload]);
  const save = async (next: T[]) => { try { await host.storage.set(key, next); setRows(next); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not save data."); } };
  return { rows, loading, error, save, reload };
}

function TasksModule({ host }: { host: HostSDK }) {
  const [tasks, setTasks] = useState<HostTask[]>([]); const [title, setTitle] = useState(""); const [priority, setPriority] = useState("medium"); const [repeat, setRepeat] = useState("none"); const [error, setError] = useState(""); const [extra, setExtra] = useState<Record<string, { repeat: string; subtasks: string[] }>>({});
  const load = useCallback(async () => { try { setTasks(await host.tasks.list()); setExtra((await host.storage.get<Record<string, { repeat: string; subtasks: string[] }>>("task-extras")) || {}); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load tasks."); } }, [host]);
  useEffect(() => { void load(); }, [load]);
  const add = async () => { const clean = title.trim(); if (!clean) return; try { const dueDate = inferDate(clean); const task = await host.tasks.add({ title: clean, priority, dueDate }); const nextExtra = { ...extra, [task.id]: { repeat, subtasks: [] } }; await host.storage.set("task-extras", nextExtra); setExtra(nextExtra); setTasks(current => [task, ...current]); setTitle(""); setRepeat("none"); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not add task."); } };
  const toggle = async (task: HostTask) => { try { await host.tasks.complete(task.id, !task.completed); if (!task.completed && ["daily", "weekly"].includes(extra[task.id]?.repeat)) { const shift = extra[task.id].repeat === "daily" ? 1 : 7; const nextDate = task.dueDate ? new Date(`${task.dueDate}T12:00:00`) : new Date(); nextDate.setDate(nextDate.getDate() + shift); const followUp = await host.tasks.add({ title: task.title, priority: task.priority, dueDate: nextDate.toISOString().slice(0, 10) }); const nextExtra = { ...extra, [followUp.id]: extra[task.id] }; await host.storage.set("task-extras", nextExtra); setExtra(nextExtra); } await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not update task."); } };
  const addSubtask = async (task: HostTask) => { const name = window.prompt("Add a small subtask"); if (!name?.trim()) return; const next = { ...extra, [task.id]: { repeat: extra[task.id]?.repeat || "none", subtasks: [...(extra[task.id]?.subtasks || []), name.trim()] } }; try { await host.storage.set("task-extras", next); setExtra(next); } catch (e) { setError(e instanceof Error ? e.message : "Could not save subtask."); } };
  const active = tasks.filter(task => !task.completed); const today = new Date().toISOString().slice(0, 10);
  return <><p className="module-lead">A clear list makes it easier to start. Dates like “tomorrow” or “Friday” are picked up as due dates.</p><form className="module-form-row" onSubmit={e => { e.preventDefault(); void add(); }}><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Add a task… e.g. call mom Friday"/><select value={priority} onChange={e => setPriority(e.target.value)} aria-label="Priority"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><select value={repeat} onChange={e => setRepeat(e.target.value)} aria-label="Repeat"><option value="none">No repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select><button className="apps-button primary" disabled={!title.trim()}>Add task</button></form>{error && <p className="module-error-inline">{error}</p>}<div className="module-list-head"><b>Today and next up</b><span>{active.length} open</span></div><div className="module-list">{tasks.filter(task => !task.completed).sort((a,b) => (a.dueDate || "9999").localeCompare(b.dueDate || "9999")).map(task => <div className="module-task" key={task.id}><button className="module-check" aria-label="Complete task" onClick={() => void toggle(task)}/><div className="module-task-body"><b>{task.title}</b><span>{task.dueDate === today ? "Today" : task.dueDate || "No due date"} · {task.priority}{extra[task.id]?.repeat !== "none" && ` · Repeats ${extra[task.id]?.repeat}`}</span>{(extra[task.id]?.subtasks || []).map((sub, i) => <small key={`${task.id}-${i}`}>↳ {sub}</small>)}</div><button className="module-link" onClick={() => void addSubtask(task)}>＋ Subtask</button></div>)}{!active.length && <ModuleEmpty title="Your task list is clear" text="Add one small next step to get moving."/>}</div></>;
}

function inferDate(text: string) { const lower = text.toLowerCase(); const date = new Date(); if (lower.includes("tomorrow")) date.setDate(date.getDate() + 1); else if (lower.includes("today")) return date.toISOString().slice(0, 10); else { const weekdays = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]; const day = weekdays.findIndex(name => lower.includes(name)); if (day < 0) return null; const delta = (day - date.getDay() + 7) % 7 || 7; date.setDate(date.getDate() + delta); } return date.toISOString().slice(0, 10); }

type Habit = SavedRow & { title: string; checks: string[]; createdAt: string };
function HabitsModule({ host }: { host: HostSDK }) {
  const store = useCollection<Habit>(host, "habits"); const [title, setTitle] = useState(""); const [error, setError] = useState(""); const day = new Date().toISOString().slice(0, 10);
  const add = async () => { if (!title.trim()) return; await store.save([{ id: crypto.randomUUID(), title: title.trim(), checks: [], createdAt: day }, ...store.rows]); setTitle(""); };
  const check = async (habit: Habit) => { const checks = habit.checks.includes(day) ? habit.checks.filter(item => item !== day) : [...habit.checks, day]; await store.save(store.rows.map(item => item.id === habit.id ? { ...item, checks } : item)); };
  return <><p className="module-lead">Small, repeatable actions are easier to keep than perfect routines.</p><form className="module-form-row" onSubmit={e => { e.preventDefault(); void add(); }}><input value={title} onChange={e => setTitle(e.target.value)} placeholder="A habit you want to build"/><button className="apps-button primary" disabled={!title.trim()}>Create habit</button></form>{store.error && <p className="module-error-inline">{store.error}</p>}<div className="module-list-head"><b>Today’s habits</b><span>{store.rows.filter(row => row.checks.includes(day)).length}/{store.rows.length} checked</span></div><div className="module-list">{store.rows.map(habit => <div className="module-task" key={habit.id}><button className={`module-check ${habit.checks.includes(day) ? "checked" : ""}`} aria-label="Log habit" onClick={() => void check(habit)}>{habit.checks.includes(day) && <Check size={14}/>}</button><div className="module-task-body"><b>{habit.title}</b><span>{habit.checks.length} {habit.checks.length === 1 ? "day" : "days"} logged · {streak(habit.checks)} day streak</span></div><button className="module-link" onClick={() => void store.save(store.rows.filter(row => row.id !== habit.id))}><Trash2 size={14}/></button></div>)}{!store.rows.length && <ModuleEmpty title="Start with one habit" text="Try a short walk, reading, or a five-minute reset."/>}</div></>;
}
function streak(checks: string[]) { const days = new Set(checks); const d = new Date(); let count = 0; while (days.has(d.toISOString().slice(0, 10))) { count++; d.setDate(d.getDate() - 1); } return count; }

type JournalEntry = SavedRow & { date: string; mood: string; tags: string; text: string };
function JournalModule({ host, userName }: { host: HostSDK; userName: string }) {
  const store = useCollection<JournalEntry>(host, "entries"); const [text, setText] = useState(""); const [mood, setMood] = useState("Okay"); const [tags, setTags] = useState(""); const [summary, setSummary] = useState(""); const [busy, setBusy] = useState(false); const day = new Date().toISOString().slice(0, 10);
  const save = async () => { if (!text.trim()) return; const existing = store.rows.find(row => row.date === day); const entry = { id: existing?.id || crypto.randomUUID(), date: day, mood, tags: tags.trim(), text: text.trim() }; await store.save([entry, ...store.rows.filter(row => row.date !== day)]); setText(""); };
  const weekly = async () => { if (!store.rows.length) return; setBusy(true); try { setSummary(await host.ai.summarize(store.rows.filter(row => Date.now() - new Date(row.date).getTime() <= 7 * 86400000).map(row => `${row.date} · ${row.mood}: ${row.text}`).join("\n"))); } catch (e) { setSummary(e instanceof Error ? e.message : "Could not summarize your entries."); } finally { setBusy(false); } };
  return <><p className="module-lead">A private place to notice what’s changing. Start with a prompt: what felt easier today than last week, {userName}?</p><div className="module-editor"><div className="module-editor-row"><input value={tags} onChange={e => setTags(e.target.value)} placeholder="Tags, separated by commas"/><select value={mood} onChange={e => setMood(e.target.value)}><option>Great</option><option>Good</option><option>Okay</option><option>Low</option><option>Stressed</option></select></div><textarea value={text} onChange={e => setText(e.target.value)} placeholder="Write a few lines about today…"/><div className="module-actions"><button className="apps-button primary" onClick={() => void save()} disabled={!text.trim()}>Save today’s entry</button><button className="apps-button" onClick={() => void weekly()} disabled={busy || !store.rows.length}>{busy ? "Thinking…" : "Summarize this week"}</button></div>{summary && <div className="module-ai-result"><Sparkles size={16}/><p>{summary}</p></div>}</div><div className="module-list-head"><b>Recent entries</b><span>{store.rows.length} saved</span></div>{store.rows.slice(0,8).map(entry => <article className="module-record" key={entry.id}><small>{entry.date} · {entry.mood}{entry.tags && ` · ${entry.tags}`}</small><p>{entry.text}</p></article>)}{!store.rows.length && <ModuleEmpty title="Your first page starts here" text="Entries save to your private Daywell account."/>}{store.error && <p className="module-error-inline">{store.error}</p>}</>;
}

type Note = SavedRow & { title: string; body: string; folder: string; tags: string };
function NotesModule({ host }: { host: HostSDK }) {
  const store = useCollection<Note>(host, "notes"); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [folder, setFolder] = useState("Inbox"); const [tags, setTags] = useState(""); const [query, setQuery] = useState(""); const [result, setResult] = useState(""); const [busy, setBusy] = useState(false);
  const capture = async () => { if (!body.trim()) return; await store.save([{ id: crypto.randomUUID(), title: title.trim() || body.trim().split("\n")[0].slice(0, 80), body: body.trim(), folder, tags: tags.trim() }, ...store.rows]); setTitle(""); setBody(""); setTags(""); };
  const extract = async (note: Note) => { setBusy(true); try { setResult(await host.ai.extract(note.body)); } catch (e) { setResult(e instanceof Error ? e.message : "Could not process note."); } finally { setBusy(false); } };
  const shown = store.rows.filter(row => `${row.title} ${row.body} ${row.tags} ${row.folder}`.toLowerCase().includes(query.toLowerCase()));
  return <><p className="module-lead">Catch an idea before it gets away. Notes are searchable and sync through your Daywell account.</p><div className="module-editor"><input className="module-full-input" value={title} onChange={e => setTitle(e.target.value)} placeholder="Title (optional)"/><textarea value={body} onChange={e => setBody(e.target.value)} placeholder="Capture a thought, detail, or next step…"/><div className="module-editor-row"><input value={folder} onChange={e => setFolder(e.target.value)} placeholder="Folder"/><input value={tags} onChange={e => setTags(e.target.value)} placeholder="Tags"/><button className="apps-button primary" onClick={() => void capture()} disabled={!body.trim()}>Capture note</button></div></div><label className="module-search"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search your notes"/></label>{result && <div className="module-ai-result"><Sparkles size={16}/><p>{result}</p></div>}<div className="module-list-head"><b>Recent captures</b><span>{shown.length} notes</span></div>{shown.slice(0,12).map(note => <article className="module-record" key={note.id}><small>{note.folder} {note.tags && `· ${note.tags}`}</small><b>{note.title}</b><p>{note.body}</p><button className="module-link" disabled={busy} onClick={() => void extract(note)}>{busy ? "Working…" : "Find action items"}</button></article>)}{!shown.length && <ModuleEmpty title="No matching notes" text="Capture a quick note above, then find it here."/>}{store.error && <p className="module-error-inline">{store.error}</p>}</>;
}

type Expense = SavedRow & { title: string; amount: number; category: string; date: string };
function MoneyModule({ host }: { host: HostSDK }) {
  const store = useCollection<Expense>(host, "expenses"); const [title, setTitle] = useState(""); const [amount, setAmount] = useState(""); const [category, setCategory] = useState("Other"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const categorize = async () => { if (!title.trim()) return; setBusy(true); try { const answer = await host.ai.generate(title); setCategory(["Food", "Transport", "Home", "Health", "Learning", "Shopping", "Bills", "Other"].find(x => answer.toLowerCase().includes(x.toLowerCase())) || "Other"); } catch (e) { setError(e instanceof Error ? e.message : "Could not suggest a category."); } finally { setBusy(false); } };
  const add = async () => { const value = Number(amount); if (!title.trim() || !Number.isFinite(value) || value <= 0) return; await store.save([{ id: crypto.randomUUID(), title: title.trim(), amount: value, category, date: new Date().toISOString().slice(0, 10) }, ...store.rows]); setTitle(""); setAmount(""); };
  const weekStart = new Date(); weekStart.setDate(weekStart.getDate() - 6); const weekly = store.rows.filter(row => new Date(`${row.date}T12:00:00`) >= weekStart).reduce((sum, row) => sum + row.amount, 0);
  return <><p className="module-lead">Keep a simple record of day-to-day spending. This is a personal log, not a bank connection.</p><div className="money-summary"><span>Last 7 days</span><strong>KES {weekly.toLocaleString("en-KE", { maximumFractionDigits: 2 })}</strong><small>{store.rows.filter(row => new Date(`${row.date}T12:00:00`) >= weekStart).length} expenses logged</small></div><div className="module-form-row"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. lunch with a friend"/><input className="amount-input" type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Amount (KES)"/><select value={category} onChange={e => setCategory(e.target.value)}>{["Food", "Transport", "Home", "Health", "Learning", "Shopping", "Bills", "Other"].map(item => <option key={item}>{item}</option>)}</select><button className="apps-button" disabled={busy || !title.trim()} onClick={() => void categorize()}>{busy ? "Thinking…" : "Suggest"}</button><button className="apps-button primary" disabled={!title.trim() || Number(amount) <= 0} onClick={() => void add()}>Log expense</button></div>{(error || store.error) && <p className="module-error-inline">{error || store.error}</p>}<div className="module-list-head"><b>Recent spending</b><span>{store.rows.length} entries</span></div>{store.rows.slice(0,20).map(row => <div className="module-task" key={row.id}><div className="module-money-icon">{row.category.slice(0,1)}</div><div className="module-task-body"><b>{row.title}</b><span>{row.date} · {row.category}</span></div><strong>KES {row.amount.toLocaleString("en-KE", { maximumFractionDigits: 2 })}</strong></div>)}{!store.rows.length && <ModuleEmpty title="Your spending log starts here" text="Add an expense to see the week's total."/>}</>;
}

function ModuleEmpty({ title, text }: { title: string; text: string }) { return <div className="module-empty"><div><Sparkles size={19}/></div><b>{title}</b><p>{text}</p></div>; }

export default function AppsStore({ moduleId, userName, onOpenModule, onOpenStore, onInstalledChange }: Props) {
  const [tab, setTab] = useState("Featured"); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All categories"); const [installed, setInstalled] = useState<Installed[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [detail, setDetail] = useState<ModuleManifest | null>(null); const [installTarget, setInstallTarget] = useState<ModuleManifest | null>(null); const [granted, setGranted] = useState<ModulePermission[]>([]); const [busy, setBusy] = useState(false); const [confirmUninstall, setConfirmUninstall] = useState<ModuleManifest | null>(null);
  const load = useCallback(async () => { try { const response = await api<{ installed: Installed[] }>("/api/modules"); setInstalled(response.installed || []); onInstalledChange?.(response.installed || []); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load the Apps catalog."); } finally { setLoading(false); } }, [onInstalledChange]);
  useEffect(() => { void load(); }, [load]);
  const installedIds = useMemo(() => new Set(installed.filter(item => item.enabled).map(item => item.moduleId)), [installed]);
  const selectedModule = moduleId ? moduleCatalog.find(item => item.id === moduleId) : undefined;
  const installation = selectedModule ? installed.find(item => item.moduleId === selectedModule.id) : undefined;
  useEffect(() => { const registry = new ModuleSlotRegistry(); for (const app of installed.filter(item => item.enabled)) { const manifest = moduleCatalog.find(item => item.id === app.moduleId); if (manifest) registry.register(manifest); } window.dispatchEvent(new CustomEvent("daywell:module-slots", { detail: registry.list() })); return () => { registry.clear(); window.dispatchEvent(new CustomEvent("daywell:module-slots", { detail: [] })); }; }, [installed]);
  const filtered = moduleCatalog.filter(item => (tab === "Installed" ? installedIds.has(item.id) : true) && (category === "All categories" || item.category === category) && `${item.name} ${item.description} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  const install = async () => { if (!installTarget) return; setBusy(true); setError(""); try { await api("/api/modules", { method: "POST", body: JSON.stringify({ action: "install", moduleId: installTarget.id, permissions: granted }) }); await load(); setDetail(null); setInstallTarget(null); setTab("Installed"); } catch (e) { setError(e instanceof Error ? e.message : "Install failed."); } finally { setBusy(false); } };
  const uninstall = async (deleteData: boolean) => { if (!confirmUninstall) return; setBusy(true); try { await api("/api/modules", { method: "POST", body: JSON.stringify({ action: "uninstall", moduleId: confirmUninstall.id, deleteData }) }); await load(); if (moduleId === confirmUninstall.id) onOpenStore(); setConfirmUninstall(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not uninstall this app."); } finally { setBusy(false); } };
  const update = async (manifest: ModuleManifest) => { setBusy(true); try { const current = installed.find(item => item.moduleId === manifest.id); await api("/api/modules", { method: "POST", body: JSON.stringify({ action: "update", moduleId: manifest.id, permissions: current?.permissions || [] }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not update app."); } finally { setBusy(false); } };
  if (moduleId) return <div className="apps-page"><button className="apps-back" onClick={onOpenStore}><ArrowLeft size={16}/> Back to Apps</button>{selectedModule && installation ? <ModulePanel manifest={selectedModule} permissions={installation.permissions} userName={userName}/> : <ModuleEmpty title="This app isn’t installed" text="Open the store and install it to use its features."/>}</div>;
  if (loading) return <div className="apps-page"><ModuleEmpty title="Opening the store…" text="Loading your installed apps."/></div>;
  const tabNames = ["Featured", "Installed", "Categories", "Updates"];
  const updateCandidates = installed.filter(item => { const current = moduleCatalog.find(module => module.id === item.moduleId); return current && current.version !== item.version; });
  return <div className="apps-page">
    <div className="apps-hero"><div><div className="apps-kicker"><Sparkles size={14}/> DAYWELL APPS</div><h2>Tools that fit your day.</h2><p>Small, focused apps that work with your Daywell goals, account, and saved data.</p></div><div className="apps-hero-mark">✳</div></div>
    <div className="apps-toolbar"><div className="apps-tabs">{tabNames.map(item => <button key={item} className={tab === item ? "selected" : ""} onClick={() => setTab(item)}>{item}{item === "Installed" && installed.length > 0 && <small>{installed.length}</small>}{item === "Updates" && updateCandidates.length > 0 && <small>{updateCandidates.length}</small>}</button>)}</div><label className="apps-search"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Find an app"/></label></div>
    <div className="apps-filter-row"><label><span>Category</span><select value={category} onChange={e => setCategory(e.target.value)}><option>All categories</option>{categories.map(item => <option key={item}>{item}</option>)}</select></label><span className="apps-result-count">{filtered.length} apps</span></div>
    {error && <p className="apps-error" role="alert">{error}</p>}
    {tab === "Categories" ? <div className="apps-category-grid">{categories.map(item => <button key={item} onClick={() => { setCategory(item); setTab("Featured"); }}><span>{moduleCatalog.filter(app => app.category === item).length.toString().padStart(2, "0")}</span><b>{item}</b><ArrowRight size={15}/></button>)}</div> : tab === "Updates" ? updateCandidates.length ? <div className="apps-grid">{updateCandidates.map(installedItem => { const app = moduleCatalog.find(item => item.id === installedItem.moduleId)!; return <article key={app.id} className="apps-card"><div className="apps-card-top"><div className="module-icon">{app.icon}</div><span className="apps-badge">Update available</span></div><b>{app.name}</b><p>{app.changelog[0]}</p><button className="apps-button primary" onClick={() => void update(app)} disabled={busy}>Update to {app.version}</button></article>; })}</div> : <ModuleEmpty title="You’re up to date" text="New app versions and their changes will appear here."/> : filtered.length ? <div className="apps-grid">{filtered.map(app => <article key={app.id} className="apps-card"><button className="apps-card-main" onClick={() => setDetail(app)}><div className="apps-card-top"><div className="module-icon">{app.icon}</div><span className="apps-category-pill">{app.category}</span></div><b>{app.name}</b><p>{app.description}</p></button><div className="apps-card-meta"><span>{formatSize(app.sizeKb)}</span><span>{app.rating ? `${app.rating.toFixed(1)} ★` : "New · no reviews"}</span><span>{app.permissions.length} permissions</span></div><div className="apps-card-actions">{installedIds.has(app.id) ? <button className="apps-button primary" onClick={() => onOpenModule(app.id)}>Open <ArrowRight size={14}/></button> : <button className="apps-button" onClick={() => setDetail(app)}>Details</button>}{installedIds.has(app.id) && <button className="apps-icon-button" aria-label="Uninstall" onClick={() => setConfirmUninstall(app)}><Trash2 size={15}/></button>}</div></article>)}</div> : <ModuleEmpty title={tab === "Installed" ? "Your collection is ready for its first app" : "No apps match that search"} text={tab === "Installed" ? "Install a small tool to make Daywell fit your routine." : "Try another name or category."}/>}
    {installed.length > 0 && tab === "Featured" && <section className="apps-widget-strip"><div><span className="apps-kicker">YOUR APPS</span><h3>Pick up where you left off</h3></div><div className="apps-widget-items">{installed.filter(item => item.enabled).slice(0, 5).map(item => { const app = moduleCatalog.find(module => module.id === item.moduleId); return app && <button key={app.id} onClick={() => onOpenModule(app.id)}><span className="module-icon small">{app.icon}</span><b>{app.name}</b><ArrowRight size={14}/></button>; })}</div></section>}
    {detail && <div className="apps-overlay" onMouseDown={e => { if (e.target === e.currentTarget) setDetail(null); }}><section className="apps-modal" role="dialog" aria-modal="true" aria-labelledby="app-detail-title"><button className="apps-close" onClick={() => setDetail(null)} aria-label="Close"><X size={19}/></button><div className="apps-detail-preview"><div className="module-icon large">{detail.icon}</div><span>{detail.category} · {detail.developer}</span><div className="apps-preview-board"><i/><i/><i/></div></div><div className="apps-detail-content"><div className="apps-kicker">APP DETAILS</div><h2 id="app-detail-title">{detail.name}</h2><p>{detail.description}</p><div className="apps-detail-stats"><span>{formatSize(detail.sizeKb)}</span><span>v{detail.version}</span><span>{detail.rating ? `${detail.rating} ★` : "No reviews yet"}</span></div><h3>Permissions</h3><ul>{detail.permissions.map(permission => <li key={permission}><CheckCircle2 size={15}/><span>{permissionCopy[permission]}</span></li>)}</ul><h3>What’s included</h3><ul><li><CheckCircle2 size={15}/><span>Appears in the Apps collection and sidebar while installed</span></li><li><CheckCircle2 size={15}/><span>Works with your Daywell account and theme</span></li>{detail.aiTools.map(tool => <li key={tool}><Sparkles size={15}/><span>AI: {tool}</span></li>)}</ul><h3>Changelog</h3><p className="apps-changelog">{detail.changelog[0]}</p><p className="apps-reviews"><Heart size={14}/> No user reviews yet. Ratings will appear when the review feature is available.</p><button className="apps-button primary apps-install" onClick={() => { if (installedIds.has(detail.id)) { setDetail(null); onOpenModule(detail.id); } else { setGranted([...detail.permissions]); setInstallTarget(detail); setDetail(null); } }}>{installedIds.has(detail.id) ? "Open app" : "Install app"}<Download size={15}/></button></div></section></div>}
    {installTarget && <div className="apps-overlay"><section className="apps-modal permission-modal" role="dialog" aria-modal="true"><button className="apps-close" onClick={() => setInstallTarget(null)}><X size={19}/></button><div className="apps-kicker">INSTALL {installTarget.name.toUpperCase()}</div><h2>Choose permissions</h2><p>Only the Daywell features you allow will be available to this app. You can revoke access later.</p><div className="permission-list">{installTarget.permissions.map(permission => <label key={permission}><input type="checkbox" checked={granted.includes(permission)} onChange={e => setGranted(current => e.target.checked ? [...current, permission] : current.filter(item => item !== permission))}/><span><b>{permissionCopy[permission]}</b><small>{permissionDetail[permission]}</small></span></label>)}</div><button className="apps-button primary apps-install" disabled={busy} onClick={() => void install()}>{busy ? "Installing…" : "Install and add to Daywell"}<ArrowRight size={15}/></button></section></div>}
    {confirmUninstall && <div className="apps-overlay"><section className="apps-modal permission-modal"><button className="apps-close" onClick={() => setConfirmUninstall(null)}><X size={19}/></button><div className="apps-kicker">REMOVE APP</div><h2>Uninstall {confirmUninstall.name}?</h2><p>The app will disappear from your collection and sidebar. Its data will stay in your Daywell account.</p><button className="apps-button apps-install" disabled={busy} onClick={() => void uninstall(false)}>Uninstall and keep data</button><button className="apps-danger-button" disabled={busy} onClick={() => { if (window.confirm(`Permanently delete all ${confirmUninstall.name} data?`)) void uninstall(true); }}>Delete app and its data</button></section></div>}
  </div>;
}

function formatSize(sizeKb: number) { return sizeKb < 1024 ? `${sizeKb} KB` : `${(sizeKb / 1024).toFixed(1)} MB`; }
const permissionCopy: Record<ModulePermission, string> = { storage: "App data", "tasks.read": "Read your tasks", "tasks.write": "Add and update tasks", ai: "AI tools", notifications: "Reminders" };
const permissionDetail: Record<ModulePermission, string> = { storage: "Save this app’s own data in your Daywell account.", "tasks.read": "Show your existing task list.", "tasks.write": "Create and complete tasks in your workspace.", ai: "Send the text you choose to your connected AI provider.", notifications: "Request browser notification permission for reminders." };
