import Link from "next/link";
import "../legal.css";

const whatsapp = "https://wa.me/254798081280?text=Daywell%20privacy%20request";

export const metadata = { title: "Privacy Policy | Daywell", description: "How Daywell handles account and workspace information." };

export default function PrivacyPage() {
  return <main className="legal-page"><div className="legal-wrap"><Link className="legal-brand" href="/">daywell<span>.</span></Link><article className="legal-card"><p className="legal-updated">Effective date: 26 September 2026</p><h1>Privacy Policy</h1><p>This policy explains how Daywell, operated by Baby Seven, handles information when you use the Daywell website or mobile app. We have written it for our current product and will update it when our practices change.</p>
    <h2>Information we handle</h2><p>When you create an account, we collect your name, email address, chosen profile role and a password hash. Your workspace can contain goals, tasks, reminders, focus sessions, check-ins and mood notes, AI conversations, and writing projects. We also store session records and basic timestamps needed to run the service.</p><p>If you connect an AI provider, Daywell stores the provider name, model, optional endpoint and your API key in encrypted form. We do not return the stored key to your browser. If you use browser notifications, your browser may display reminder notifications while Daywell is open.</p>
    <h2>How we use information</h2><p>We use this information to create and secure your account, save and sync your workspace, respond to your requests, provide AI features you choose to use, enforce service limits, troubleshoot failures, and protect the service from abuse. We do not sell personal information or use workspace content for advertising.</p>
    <h2>AI providers</h2><p>When you use an AI feature, the prompt and relevant conversation or workspace context are sent to the AI provider configured for your account, or to Daywell’s shared provider when that feature is enabled. The provider returns the response, which may be saved in your workspace. If you bring your own provider key, it is used server-side to make that request. Each provider handles requests under its own terms and privacy policy; review those terms before connecting it. Avoid sending sensitive information you do not want processed by that provider.</p>
    <h2>Service providers and international processing</h2><p>Daywell uses Vercel to host the app and Neon to host its PostgreSQL database. These providers process information to operate the service and may process or store it in data centres outside Kenya. AI providers process information only when an AI feature is used. We require appropriate safeguards from service providers and limit access to what is needed to operate Daywell.</p>
    <h2>Retention and security</h2><p>We keep account and workspace information while the account is active. You can download a JSON copy of your workspace in Settings. To request account deletion or correction, contact us using the link below; we will verify the request and remove information unless we must retain it for a lawful reason. Passwords are hashed, session tokens are stored as hashes, and provider API keys are encrypted at rest. No online service can guarantee absolute security.</p>
    <h2>Your choices and rights</h2><p>You may access and correct information in your workspace, download your data, sign out, and request deletion or object to processing by contacting us. You may also lodge a complaint with Kenya’s Office of the Data Protection Commissioner. Rights and response periods are subject to applicable law.</p>
    <h2>Children</h2><p>Daywell is not designed to collect personal information from children under 18 without the consent and involvement of a parent or guardian. If you believe a child has created an account without appropriate consent, contact us so we can review and address it.</p>
    <h2>Changes and contact</h2><p>We may update this policy as Daywell changes. We will post the revised version here with a new effective date. For privacy requests or questions, contact Baby Seven on <a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp at 0798 081 280</a>.</p>
    <div className="legal-actions"><Link href="/terms">Terms of Service</Link><Link href="/">Back to Daywell</Link><a href="https://www.odpc.go.ke/rights-of-a-data-subject/" target="_blank" rel="noreferrer">Kenya data subject rights</a></div></article></div></main>;
}
